spring:
  datasource:
    url: jdbc:mysql://localhost:3306/malldb
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/*.xml
server:
  port: 8090
  servlet:
    context-path: /